FROM ubuntu:trusty
## El ENTRYPOINT especifica el ejecutable que usará el contenedor,y CMD se corresponde con los parámetros a usar con dicho ejecutable.
ENTRYPOINT [ "/bin/ping", "-c", "3"]
CMD ["localhost"]
# CMD ["/bin/ping", "-c", "3", "localhost"]

