version: "3.3"

services:
  app:
    build: .
    # environment:
    #   MONGO_URL: "mongodb://db:27017/test"
    # depends_on:
    #   - db
    ports:
      - "8080:80"
    networks:
      - laboratorio

networks:
    laboratorio:
        # use the bridge driver, but enable IPv6
        name: laboratorios
        driver: bridge
        driver_opts:
           attachable: "true"