version: "3.3"

services:
  app:
    build: .
    # environment:
    #   MONGO_URL: "mongodb://db:27017/test"
    # depends_on:
    #   - db
    ports:
      - "8080:80"
    networks:
      - frontend

networks:
  frontend:
    name: laboratorios
    driver: bridge
    attachable: true